### ISSUE TITLE
about your comment plugin

### ISSUE THREAD

**Issue by TimFang4162** [wrj2009/wrj2009.github.io#1]
hexo主题很棒!  
但是能不能用[valine/](https://valine.js.org/)而不是gitalk  
valine虽然配置麻烦点但是速度很快~~不像gitalk半天加载不出来(针对无梯用户)~~  
差不多这样  
![图片](https://user-images.githubusercontent.com/60050973/109235537-cc719780-7808-11eb-97cc-1b3f7eb144f2.png)  
https://timfang.gitee.io/

**Comment by wrj2009** [comment]
确实，有的时候还会有bug。当时看文档的时候我觉得Gitalk似乎更好……  
~~我绝对不会告诉你“野兽先辈”的评论是我发的~~

**Comment by wrj2009** [comment]
啊……配置真的是麻烦，反正我是不想实名认证了

**Comment by wrj2009** [comment]
@Tim-Fang 我打算以后换个主题，这个主题 bug 有亿点多

**Comment by wrj2009** [comment]
> 确实，有的时候还会有bug。当时看文档的时候我觉得Gitalk似乎更好……
> ~我绝对不会告诉你“野兽先辈”的评论是我发的~

而且我用的不是 MacOS
